apiVersion: v1
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <body style="background-color:{{.Values.bgColor}};">

    <h1>Welcome to {{.Values.orgName}}</h1>
    <p>{{.Values.appName}} app is up!!! </p>
  

    </body>
    </html>
kind: ConfigMap
metadata:
  name: nks-web
  labels:
    app: {{.Values.appName}}
